### Multinomial Naive Bayes Classifier

In [1]:
# importing important libraries
import os, sys
import pickle
import json
from sklearn.naive_bayes import MultinomialNB as nb
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

#### Reading train and test data

In [2]:
cwd = os.getcwd() #Current working directory

#Read training data
f = open(os.path.join(cwd, r'train.pkl'), 'rb')
(X_data, X_label) = pickle.load(f)
f.close()

#Read test data
f = open(os.path.join(cwd, r'test.pkl'), 'rb')
(Y_data, Y_label) = pickle.load(f)
f.close()

train = []
trainLabel = []

label2no = {u'supporting':0, u'querying':1, u'denying':2, u'comment':3}

#Convert list of lists to nd array (Training dataset)
for key in X_label.keys():
    train.append(X_data[key])
    trainLabel.append(label2no[X_label[key]])

train = np.array(train)
trainLabel = np.array(trainLabel)
min1 = train.min()
# print (min1)
for i in range(len(train)):
    for j in range(len(train[i])):
        train[i][j] = train[i][j] + abs(min1) 

#Naive Bayes Classifier Training
nb_clf = nb().fit(train, trainLabel.transpose())

#Convert list of lists to nd array (Testing dataset)
test = []
testLabel = []

for key in Y_label.keys():
    test.append(Y_data[key])
    testLabel.append(label2no[Y_label[key]])

test = np.array(test)
testLabel = np.array(testLabel)
min1 = test.min()
for i in range(len(test)):
    for j in range(len(test[i])):
        test[i][j] += min1


#### NB classification results

In [3]:
#Naive Bayes Classifier Testing
predicted = nb_clf.predict(test)

print("Classification accuracy: ", accuracy_score(testLabel, predicted))
print("Confusion matrix: ", confusion_matrix(testLabel, predicted))
target_names = ['supporting', 'querying', 'denying', 'comment']
print(classification_report(testLabel, predicted, target_names=target_names))
#Accuracy
print(np.mean(predicted == testLabel)*100)

Classification accuracy:  0.6850533807829181
Confusion matrix:  [[123   0   0 102]
 [  6   0   0  93]
 [ 12   0   0  75]
 [ 66   0   0 647]]
              precision    recall  f1-score   support

  supporting       0.59      0.55      0.57       225
    querying       0.00      0.00      0.00        99
     denying       0.00      0.00      0.00        87
     comment       0.71      0.91      0.79       713

    accuracy                           0.69      1124
   macro avg       0.32      0.36      0.34      1124
weighted avg       0.57      0.69      0.62      1124

68.50533807829181


C:\Users\Chandni Dave\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
